version: "3.9"
services:
  telegram-adapter:
    image: telegram-adapter:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    # volumes:
    #   - /Users/nicholas/Databases:/app/DatabasesMount
    env_file:
      - .env.dev
